
remote_theme: jeffreytse/jekyll-theme-yat@v1.10.0
title: Hacking Odyssey
author: Vamsi Surakarapu

description: >-
  Hack-Odyssey is a personal portfolio where I showcase my skills and projects in multiple fields like cybersecurity, Java, machine learning, web development, blockchain, and more. Its a collection of real-world applications that highlight my problem-solving abilities and creativity. This portfolio reflects my journey through different domains, demonstrating how I tackle challenges and come up with innovative solutions. Whether its securing systems, building apps, or diving into new technologies, Hack-Odyssey is where you can see how I apply my knowledge in practice.
yat: 
  date_format: "%b %d, %Y"
defaults:
  home:
      heading: "Hacking Odyssey"
      subheading: "There is nothing we can do. So I wish for strength... to shatter fate."
      banner: "home.jpg"
      
favicon: "https://avatars.githubusercontent.com/u/85192850"
night_mode: "on"

# config it by the front matter for one specific post
# banner:
#   video: null             # Video banner source
#   loop: true              # Video loop
#   volume: 0               # Video volume (100% is 1.0)
#   start_at: 0             # Video start time
#   image: null             # Image banner source
#   opacity: 1.0            # Banner opacity (100% is 1.0)
#   background: "rgba(0, 0, 0, 0.8)"  # Banner background (Could be a image)
#   height: "640px"         # Banner default height
#   min_height: null        # Banner minimum height
#   heading_style: null     # Custom heading style (e.g. "font-weight: bold; text-decoration: underline")
#   subheading_style: null  # Custom subheading style (e.g. color: gold)

# Translate languges
# langs refer to https://cloud.google.com/translate/docs/languages
translate_langs:
  - lang: en
    img: https://cdn.countryflags.com/thumbs/united-states-of-america/flag-400.png
    text: English

  - lang: fr
    img: https://cdn.countryflags.com/thumbs/france/flag-400.png
    text: French

  - lang: ja
    img: https://cdn.countryflags.com/thumbs/japan/flag-400.png
    text: Japanese
# brand_color: "#389092"
header_pages:
  - index.html
  - categories.html
  - archives.html
  - about.html

# Pagination setting
paginate: 5

disqus:
  shortname: "Hack Odyssey"
